# Site settings
title: Dr. Li, Xue（李雪）
email: lixue.science@gmail.com
description: Academic webpage of Li, Xue
baseurl: ""
url: ""
affiliation: I am a doctoral student of the <a href="http://en.hitsz.edu.cn" target="_blank">Computer Science Department</a> at the Harbin Institute of Technology

# Google analytics ID
#google_analytics: UA-176412042-1

# Location info. (shown in footer)
location: >
  Coordinates: <br/>
  Multi-functional Building<br/>
  Harbin Institute of Technology <br/>
  Xidazhi Street 92<br/>
  Habin, Heilongjiang 150001<br/>

# Contact info. (shown in footer)
contact: >
    Contact Li,Xue via email: <a href="mailto:lixue.science@gmail.com" target="_blank">lixue.science@gmail.com</a> <br/>
    
# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: talks
  - name: flight
#  - name: service
# - name: research
# - name: software
# - name: team
# - name: teaching

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
